import { REACT_APP_IP_ADDRESS, REACT_APP_STRIPE_PUBLIC_API_KEY, REACT_APP_FONT, REACT_APP_URL } from 'react-native-dotenv'

export default {
  REACT_APP_IP_ADDRESS,
  REACT_APP_STRIPE_PUBLIC_API_KEY,
  REACT_APP_FONT,
  REACT_APP_URL
};
